FROM alpine:latest

RUN apk add \
				libpcre3 \
				libpcre3-dbg \
				libpcre3-dev \
				build-essential \
				libpcap-dev \
				libyaml-0-2 \ 
				libyaml-dev \
				pkg-config \
				zlib1g \
				zlib1g-dev \
        make \
				libmagic-dev \
				jansson \
				jansson-dev \
				suricata
