apiVersion: v1
kind: Service
metadata:
  name: docker-snort
  namespace: snort-1
spec:
  selector:
    app: docker-snort
  type: ClusterIP  
  ports:
    - port: 30002
      targetPort: 30002
#      nodePort: 30002
