apiVersion: v1
kind: Service
metadata:
  name: docker-snort
  namespace: snort-1
spec:
  selector:
    app: docker-snort
  type: NodePort  
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 3002
