apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-8
  namespace: snort-8
  labels:
    app: sn-8
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sn-8
  template:
    metadata:
      name: sn-8
      labels:
        app: sn-8
    spec:
      terminationGracePeriodSeconds: 10      
      containers:
      - name: sn-8
        image: linton/docker-snort:latest
        stdin: true 
        tty: true
        command: 
          - '/bin/sh'
          - '-c'
          - ' snort -i eth0 -c /etc/snort/etc/snort.conf -A console'
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests: 
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
        imagePullPolicy: IfNotPresent
      hostNetwork: true  
