apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      name: resource-consumer
      labels:
        app: resource-consumer
    spec:
      containers:
      - name: resource-consumer
        image: dj80hd/resource-consumer:latest
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 500m
        imagePullPolicy: Always
        

