apiVersion: v1
kind: Service
metadata:
  name: resource-consumer
spec:
  selector:
    app: resource-consumer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30006
  type: NodePort
  selector:
    app: resource-consumer
