apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-5
  namespace: snort-5
  labels:
    app: sn-5
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sn-5
  template:
    metadata:
      name: sn-5
      labels:
        app: sn-5
    spec:
      terminationGracePeriodSeconds: 10      
      containers:
      - name: sn-5
        image: linton/docker-snort:latest
        stdin: true 
        tty: true
        command: ["/bin/sh", "-c"]
        args: ["echo \"alert icmp any any -> any any (msg:\'Pinging...\';sid:1000004;)\" >> /etc/snort/rules/local.rules & snort -i eth0 -c /etc/snort/etc/snort.conf -A console"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests: 
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
        imagePullPolicy: IfNotPresent
      hostNetwork: true  